---
- name: mint_auto
  hosts: localhost
  connection: local
  gather_facts: false

  vars:

  tasks:
    - name: create .bash_aliases
      lineinfile:
        path: /home/hugh/.bash_aliases
        line: "{{item}}"
        create: yes
      with_items:
        - alias ll="ls -ltrh --color=auto"
        - alias vi="vim"
        - alias clean="sed --in-place 's/[[:space:]]\+$//' $1"
      tags: prep

    - name: create .gitconfig
      lineinfile:
        path: /home/hugh/.gitconfig
        line: "{{item}}"
        create: yes
      with_items:
        - '[alias]'
        - lg1 = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all
        - lg2 = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all
        - lg = log --all --oneline --decorate --graph
        - '[user]'
        - email = hughwang10@gmail.com
        - name = hughwang10
      tags: prep

    - name: dist upgrade
      become: yes
      apt:
        upgrade: dist
        autoclean: yes
        autoremove: yes
        purge: yes
        update_cache: yes
      tags: prep

    - name: Update common packages
      become: yes
      apt:
        name:
          - vim
          - tree
          - sshpass
          - ipcalc
          - python-pip
          - docker.io
          - docker-compose
          - docker-registry
          - python-dev
          - libffi-dev
          - gcc
          - libssl-dev
          - python-selinux
          - lsb-core
          - chromium-browser
          - sublime-text
          - dropbox
          - meld
          - snmp
          - genisoimage
        update_cache: yes
      tags: prep

    - name: pip2 install
      become: yes
      pip:
        name:
          - pip
          # - setuptools
          - wheel
          - netaddr
          - pyVmomi
          - pysphere
          - shade
          - python-openstackclient
          - python-glanceclient
          - python-neutronclient
          - pysnmp
        executable: pip2
        state: latest
      tags: prep

    - name: Creates /etc/ansible
      become: yes
      file:
        path: /etc/ansible
        state: directory
        mode: 0755
      tags: prep

    - name: Download ansible.cfg
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/ansible/ansible/devel/examples/ansible.cfg
        dest: /etc/ansible/ansible.cfg
        mode: 0644
      tags: prep1

    - name: update ansible.cfg
      become: yes
      lineinfile:
        dest: /etc/ansible/ansible.cfg
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^#host_key_checking.*', line: 'host_key_checking = False' }
        - { regexp: '^#pipelining.*', line: 'pipelining = False' }
        - { regexp: '^#forks.*', line: 'forks = 100' }
        - { regexp: '^#roles_path.*', line: 'roles_path = /home/hugh/Dropbox/myansible/roles' }
        - { regexp: '^#inventory.*', line: 'inventory = /home/hugh/Dropbox/ansible/config/hosts' }
        - { regexp: '^#library.*', line: 'library  = /home/hugh/Dropbox/myansible/library' }
        - { regexp: '^#retry_files_enabled.*', line: 'retry_files_enabled = False' }
      tags: prep1