---
- name: mint_auto
  hosts: localhost
  connection: local
  gather_facts: false

  vars:

  tasks:
    - name: create .bash_aliases
      lineinfile:
        path: /home/hugh/.bash_aliases
        line: "{{item}}"
        create: yes
      with_items:
        - alias ll="ls -ltrh --color=auto"
        - alias vi="vim"
        - alias clean="sed --in-place 's/[[:space:]]\+$//' $1"

    - name: create .gitconfig
      lineinfile:
        path: /home/hugh/.gitconfig
        line: "{{item}}"
        create: yes
      with_items:
        - '[alias]'
        - lg1 = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all
        - lg2 = log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all
        - lg = log --all --oneline --decorate --graph
        - '[user]'
        - email = hughwang10@gmail.com
        - name = hughwang10

    - name: Update common packages
      become: yes
      apt:
        name:
          - vim
          - tree
          - python-pip
          - docker.io
          - docker-compose
          - docker-registry
          - python-dev
          - libffi-dev
          - gcc
          - libssl-dev
          - python-selinux
        update_cache: yes
      tags: update